### ISSUE TITLE
hierarchy-lookup may be the cause of hanging imports

### ISSUE THREAD

**Issue by sevko** [pelias/polygon-lookup#2]
After running several imports via [pelias/openaddresses](https://github.com/pelias/openaddresses), I noticed that they'd hang whenever I `pipe()`d data through `hierarchy-lookup`. It might be the cause of the hanging imports we see in production, and, after some digging, [these lines](https://github.com/pelias/hierarchy-lookup/blob/master/lib/stream.js#L30,#L35) look suspect:

```
function(){
  // close the adapter when done
  // @TODO: this might not be ideal in some cases
  opts.backends[0].adapter.client.close();
});
```

As per the [`through2` documentation](https://www.npmjs.com/package/through2#flushfunction), the flush function receives a callback argument that it should invoke before exiting. Adding that made the import exit as expected, but another problem popped up right before it did:

```
esclient error { [Error: No Living connections] message: 'No Living connections' }
```

I queried `localhost:9200/pelias/_count` and came up about 500 records short of what I expected. I suspect that `opts.backends[0].adapter.client.close();` globally closes connections to elasticsearch, since commenting that out resolved the problem. If we don't need it, we can get rid of the flush function entirely.

**Comment by missinglink** [comment]
Let's have a chat about this issue, it's most likely the source of the 'process not exiting' issues and we can probably do something better to avoid it.

**Comment by sevko** [comment]
This _was_ the problem for `openaddresses`, which depends on this package, and removing the flush function resolved it. `openstreetmap` doesn't replicate this code and has a [separate issue](https://github.com/pelias/openstreetmap/issues/24#issuecomment-73104671), unfortunately.
