### ISSUE TITLE
experimenting with a faster, more accurate hierarchy-lookup

### ISSUE THREAD

**Issue by sevko** [pelias/polygon-lookup#3]
I've been investigating an alternative admin-value generation solution to querying Quattroshapes in elasticsearch for a while. Here's a **tl;dr**:

Initially, we encountered a problem where lots of our address data was missing admin values, so @missinglink wrote up a couple of queries to coarse reverse-geocode points against our Quattroshapes types in ES, and bundled them up into this package. Two problems arose:
1. ES reverse geocodes by checking points against a GeohashPrefixTree or QuadTree of its polygons, and never performs an actual point-in-polygon intersection. Hence, there's imprecision around borders. The black line in the following image is the border between New Jersey and New York states in Quattro data, and red/blue points are identified as New Jersey/New York respectively.

![Elasticsearch reverse-geocoding imprecision.](https://cloud.githubusercontent.com/assets/4467604/6083107/3dd25ab2-adf4-11e4-8e19-ae38a5222254.png)

This could be mitigated by increasing the index precision, but wouldn't fully solve the problem:
![Increased index precision.](https://cloud.githubusercontent.com/assets/4467604/6083147/8b556c70-adf4-11e4-829a-b56176df3cf1.gif)
1. HTTP requests to ES are incredibly slow. Granted, we could have sped those up by making them batched and asynchronous, but never got there.

I experimented with an alternative admin value creator suggested by Al, which basically creates a local reverse geocoder: a prototype lives in the [local-rtree-lookup](https://github.com/pelias/hierarchy-lookup/tree/local-rtree-lookup) branch. It loads Quattro into memory, builds a spatial index ([rtree](http://en.wikipedia.org/wiki/R-tree)) for it, and then for each incoming point:
1. Looks it up in the index: very fast, since it's just a bunch of bounding box comparisons, and limits the set of potential intersecting polygons to just a couple.
2. If the number of candidate polygons is > 1, performs point-in-polygon intersections to determine which one actually intersects.

Since it's local and makes the additional intersection calculations, it's much faster and more accurate than the ES variant. An OpenAddresses import that took a week to index 20m records with some bad admin data now takes 16 hours to index 40m with apparently excellent admin values. A simple benchmark showed that querying elasticsearch loaded with all of Quattroshapes took 9 minutes to reverse geocode 15K points, while the local lookup took less than half a second.

**Comment by sevko** [comment]
Now that it's been battle-tested, I'm wondering how to ship it.
1. Should we keep it in this package and just do a major version bump? Sounds sensible to me, but @missinglink might want to keep these ES queries around as their own up-to-date package.
2. Should we tightly couple this to Quattroshapes? It's currently generalized for any shapefiles containing `Polygon`s and `MultiPolygon`s, but that requires a [_ton_ of configuration](https://github.com/pelias/openaddresses/blob/rtree-lookup-test/lib/hierarchy_lookup.js) in the other packages that want to use it with. I say we ship it with a feature to load Quattroshapes baked in, and remove that if we start using more polygon datasets in the future.

cc @hkrishna , @missinglink , @dianashk

**Comment by hkrishna** [comment]
Thank you @sevko for this. This is a big win! We should definitely ship asap. I think keeping it in the package with a major version bump makes sense to me. But I'm up for discussing 2 as well

**Comment by dianashk** [comment]
This is huge!

I'd like to see it be generic and not tied to Quattroshapes, since I'm looking into using the OSM admin boundaries as a potential source of polygon data. Maybe consider a structure where the core module does the core logic and then write data-source-specific input plugins.

**Comment by sevko** [comment]
Right, I forgot that we might be using OSM polygons in the near future, so it sounds like a good idea to make the core functionality generalized right off the bat. Will think about how to architect it and get back to you.

**Comment by sevko** [comment]
It sounds like we'd have to publish two packages:
1. `hierarchy-lookup`, which accepts a GeoJSON array and returns a [`HierarchyLookup`](https://github.com/pelias/hierarchy-lookup/blob/local-rtree-lookup/index.js#L10) object, which can be `.search()`'d.
2. `quattroshapes-hierarchy-lookup`, which wraps `hierarchy-lookup` and exports a stream that will insert admin values using `HierarchyLookup`s loaded with Quattroshapes.

y/n?

**Comment by sevko** [comment]
Mulled it over with @dianashk and the above seems to make the most sense. Here's my rough summary of the reason why:

> We have multiple admin levels: admin0 (country), admin1 (state), admin2, etc.,
> and a Quattroshapes polygon shapefile for each. We want to perform a separate
> lookup against each of these levels, so we need an instance of a reverse
> geocoder for each, which:
> 
>   1.) ingests all the polygons for that level
>   2.) creates a spatial index based on their bounding boxes
>   3.) stores the polygons internally to perform further point-in-polygon intersections in the case of index lookup ambiguity
> 
> The `hierarchy-lookup` package currently exports a `HierarchyLookup()`
> constructor that does all of the above, and contains a `.search()` member
> method to reverse geocode a single point. It's generalized for any kind of
> polygon input, which is a win, but you need to take extra steps to get it to
> work with Quattro and in a streaming fashion:
> 
>   1.) load the Quattro shapefiles
>   2.) create an instance of HierarchyLookup for each shapefile (or admin level)
>   3.) create a stream that accepts incoming points, and calls each HierarchyLookup's .search() for any given one
>   4.) adds the names of each admin level's intersecting polygons to that point
> 
> The above steps are happening in this module in the openaddresses importer: https://github.com/pelias/openaddresses/blob/rtree-lookup-test/lib/hierarchy_lookup.js
> Since other importers will want to use a similar Quattro-based lookup (at least
> until we get more polygon datasets), we should create a package that creates
> that Quattro-lookup stream so that we don't repeat ourselves.

**Conclusion**: I'm merging `local-tree-lookup` into `master`, publishing a major version bump, and abstracting [this module](https://github.com/pelias/openaddresses/blob/rtree-lookup-test/lib/hierarchy_lookup.js) to its own package (think `hierarchy-lookup-quattroshapes`).

**Comment by sevko** [comment]
Addendum: will also rename this package to something more descriptive to reflect its rewritten functionality.

**Comment by missinglink** [comment]
Amazing work @sevko
