### ISSUE TITLE
support for typescript?

### ISSUE THREAD

**Issue by lidaof** [pelias/polygon-lookup#40]
Hi Dear author,

is it possible to make this package work with typescript? thanks.

**Comment by orangejulius** [comment]
Hi @lidaof,
As far as I know, all Javascript is valid Typescript, so no extra work should be needed for you, to use this code, right?

If you're asking if we'll add a Typescript Declarations file, the answer is probably no. The core team doesn't have any experience with Typescript and probably won't start using it any time soon. Therefore we'd be unable to review or update that file over time.

**Comment by lidaof** [comment]
i see, thank you @orangejulius
