### ISSUE TITLE
vs which-polygon?

### ISSUE THREAD

**Issue by tmcw** [pelias/polygon-lookup#5]
Is this architecturally different or does it have a different goal than [which-polygon?](https://github.com/mapbox/which-polygon)

**Comment by riordan** [comment]
There’s more than one way to do a point-in-polygon lookup, but you’re right, there’s not much of a difference between the two. They both do point-in-polygon lookups using an r-tree (we also use @mourner’s [rbush](https://github.com/mourner/rbush)) and raycasting. There’s some extra code around determining if the point’s in a donut hole of a multipolygon (which I assume which-polygon does as well). As far as I know, which-polygon didn’t exist back when we started the project.

Something something long lost twins separated at birth

**Comment by mourner** [comment]
Yeah, I wasn't aware of this module when I wrote `which-polygon`, which I needed for a quick task. Sorry for duplicating the effort here.

**Comment by riordan** [comment]
Nothing to apologize for!

Also thank you for rbush!
